# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(883, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 120, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 260, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txtplaintext = QtWidgets.QTextEdit(self.centralwidget)
        self.txtplaintext.setGeometry(QtCore.QRect(120, 120, 271, 71))
        self.txtplaintext.setObjectName("txtplaintext")
        self.txtcptext = QtWidgets.QTextEdit(self.centralwidget)
        self.txtcptext.setGeometry(QtCore.QRect(120, 240, 271, 71))
        self.txtcptext.setObjectName("txtcptext")
        self.txtsign = QtWidgets.QTextEdit(self.centralwidget)
        self.txtsign.setGeometry(QtCore.QRect(520, 240, 271, 71))
        self.txtsign.setObjectName("txtsign")
        self.txtinfomation = QtWidgets.QTextEdit(self.centralwidget)
        self.txtinfomation.setGeometry(QtCore.QRect(520, 120, 271, 71))
        self.txtinfomation.setObjectName("txtinfomation")
        self.btngenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btngenerate.setGeometry(QtCore.QRect(60, 50, 75, 41))
        self.btngenerate.setObjectName("btngenerate")
        self.btnen = QtWidgets.QPushButton(self.centralwidget)
        self.btnen.setGeometry(QtCore.QRect(60, 400, 101, 41))
        self.btnen.setObjectName("btnen")
        self.btnde = QtWidgets.QPushButton(self.centralwidget)
        self.btnde.setGeometry(QtCore.QRect(260, 400, 91, 31))
        self.btnde.setObjectName("btnde")
        self.btnsign = QtWidgets.QPushButton(self.centralwidget)
        self.btnsign.setGeometry(QtCore.QRect(510, 400, 81, 31))
        self.btnsign.setObjectName("btnsign")
        self.btninfo = QtWidgets.QPushButton(self.centralwidget)
        self.btninfo.setGeometry(QtCore.QRect(720, 400, 91, 31))
        self.btninfo.setObjectName("btninfo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 883, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA Cipher"))
        self.label_2.setText(_translate("MainWindow", "Text"))
        self.label_3.setText(_translate("MainWindow", "CIPHER TEXT"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "sign"))
        self.btngenerate.setText(_translate("MainWindow", "Generate key"))
        self.btnen.setText(_translate("MainWindow", "Encryted"))
        self.btnde.setText(_translate("MainWindow", "decryted"))
        self.btnsign.setText(_translate("MainWindow", "sign"))
        self.btninfo.setText(_translate("MainWindow", "info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
